name = "PyFITS"
uuid = "8bc99c6c-7bfa-45ed-8c8b-4447c0025491"
authors = ["Daniel Boyea <aeyobd@gmail.com>"]
version = "0.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
DataFrames = "1.7.0"
OrderedCollections = "1.8.0"
PythonCall = "0.9.24"
